name: Generate Theme

on:
  push:
    branches:
      - ongoing
  pull_request:
    branches:
      - ongoing

jobs:
  generate-theme-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: ./.github/actions/setup

      - name: Configure Git
        run: |
          git config --local user.email "denciczarko@gmail.com"
          git config --local user.name "GitHub Action"

      - name: Write Files
        run: |
          npm install
          node scripts/delete-fonts.js
          node scripts/create-config.js

      - name: Check for Changes
        id: changes
        run: |
          git status --porcelain > changes.txt
          cat changes.txt
          if [ -s changes.txt ]; then
            echo "Changes detected. Proceeding with commit."
            exit 0
          else
            echo "No changes. Skipping commit."
            exit 1
          fi

      - name: Commit Changes
        if: steps.changes.outcome == 'success'
        run: |
          git add .
          git rm -f 'tokens/palettes/default.json'
          git rm -f 'tokens/palettes/financial.json'
          git rm -f 'tokens/palettes/fitness.json'
          git rm -f 'tokens/palettes/gaming.json'
          git rm -f 'tokens/changedBrand/default.json'
          git rm -f 'tokens/changedBrand/financial.json'
          git rm -f 'tokens/changedBrand/fitness.json'
          git rm -f 'tokens/changedBrand/gaming.json'
          git status
          git commit -m "Update config"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Generated theme files"
          body: "Please review and merge these changes."
