name: Generate Theme Files

on:
  push:
    branches:
      - ongoing

jobs:
  generate-theme-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: ./.github/actions/setup

      - name: Write Files
        run: |
          npm install
          node delete-fonts.js
          node create-config.js

      - name: Configure Git
        run: |
          git config --local user.email "denciczarko@gmail.com"
          git config --local user.name "GitHub Action"

      - name: Check if Branch Exists
        id: branch-check
        run: |
          if git ls-remote --heads origin feature-generated-files | grep -q "feature-generated-files"; then
            echo "Branch exists"
            echo "::set-output name=branch_exists::true"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create Branch
        if: steps.branch-check.outputs.branch_exists == 'false'
        run: |
          git branch feature-generated-files
          git push origin feature-generated-files

      - name: Checkout Branch
        run: |
          git checkout feature-generated-files

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update config"
          git push origin feature-generated-files

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature-generated-files
          base: ongoing
          title: "Generated theme files"
          body: "Please review and merge these changes."
