name: Generate Theme

on:
  push:
    branches:
      - ongoing-test

jobs:
  generate-theme-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: ./.github/actions/setup

      - name: Configure Git
        run: |
          git config --local user.email "denciczarko@gmail.com"
          git config --local user.name "GitHub Action"

      - name: Write Files
        run: |
          npm install
          node scripts/delete-fonts.js
          node scripts/create-config.js

      - name: Commit Changes
        run: |
          git add .
          git rm -f 'tokens/palettes/default.json'
          git rm -f 'tokens/palettes/financial.json'
          git rm -f 'tokens/palettes/fitness.json'
          git rm -f 'tokens/palettes/gaming.json'
          git rm -f 'tokens/brand/default.json'
          git status
          git commit -m "Update config"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Generated theme files"
          body: "Please review and merge these changes."
