name: Write File Action

on:
  push:
    branches:
      - test

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Write config
        run: |
          node create-config.js
          git config --local user.email "denciczarko@gmail.com"
          git config --local user.name "GitHub Action"
          git add config.json
          git commit -m "Update config"
          git push
